### ISSUE TITLE
ArgumentException: Unable to find a module by assembly 'EPiServer.Forms, Version=5.2.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' (Parameter 'moduleAssembly')

### ISSUE THREAD

**Issue by bnitt** [episerver/Foundation#832] opened 2022-07-10 18:47 UTC
**Describe the bug**
After following setup guide, I received the following error:

**Screenshots**
![image](https://user-images.githubusercontent.com/60018833/178158017-c80c0590-1edf-4d3f-8a71-7e26796004d2.png)

``

**Comment by davidknipe** [comment] 2022-07-13 15:36
Found the _reason_ but don't know the _cause_. On the left a working version where the modules/_protected folder contains the actual ZIP on the right there's a whats looks like a Windows symbolic link to the package in Visual Studio. Trying to figure out why this is the case and what can be changed to configure/fix it. If you want to fix it today copy in the packages from your /.nuget/ folder and all works fine

![forms](https://user-images.githubusercontent.com/6765939/178773470-62b1ec40-6578-4c60-bd95-d9cbe841a5fd.jpg)

**Comment by valdisiljuconoks** [comment] 2022-07-13 16:13
I've seen this behaviour as well (more details - https://blog.tech-fellow.net/2021/09/03/how-to-pack-your-shell-module-for-optimizely-content-cloud/). This is related to how VS installs package and how scripts are executed at that time.

However after build package files were copied correctly (same happens on publish). But here - to launch the project you have to build it ;)

Weird indeed.

Tried `dotnet build` ?

**Comment by davidknipe** [comment] 2022-07-13 17:12
I can see the modules in the right place in the bin folder but it still complains when starting so thought it was some Dojomojo going on. Still doesn't feel right having an effective symbolic link in VS to a Nuget package in the .nuget cache location though. It's only on a specific (new build) VM I noticed it.

**Comment by joshuaonwezen** [comment] 2022-07-15 09:25
Copying the /.nuget/ folder packages doesn't seem to work for me. Has anyone been able to figure this out yet?

`Unable to find a module by assembly 'EPiServer.Forms, Version=5.2.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7' (Parameter 'moduleAssembly')`

**Comment by marisks** [comment] 2022-07-19 13:24
@joshuaonwezen You should not copy that folder, only the missing ZIP file.

P.S. Optimizely should fix the virtual path provider so that it will use sim links. The hack we are doing with modules is not the right approach to using NuGet packages.

**Comment by marisks** [comment] 2022-07-19 14:19
I had the same issue. Copied the ZIP file and the app run, but Admin does not work - issues with Forms:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/646298/179772844-92779d54-6614-4d17-891f-270432de14ce.png">
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/646298/179772970-1b282229-603d-4648-8207-08d76c3db1bd.png">

And some weird exception:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/646298/179773042-22e2fcfb-419c-45d4-9edc-0751ee2899c2.png">

Has anyone successfully run the latest version?

**Comment by ashishgururani1** [comment] 2022-08-03 16:48
I have the same issue which for now is solved my moving the zip file. Would love to get a fix for this.

**Comment by kking5464** [comment] 2022-08-06 03:40
I'm running into this issue on a mac using .net6 and can't seem to get this working. 

Can someone who has created a temporary fix provide more specifics? 

I have the zip file in the bin/Debug/net.60/modules/_protected folders for both EPiServer.Forms and EPiServer.Forms.UI. I even see them in finder so I'm not sure where the group is saying to copy them. 

And obviously, I'm not sure why the error is happening anyway, as those packages are installed (even did a dotnet install for both). 

Any help would be greatly appreciated - relatively urgent POC.

**Comment by kking5464** [comment] 2022-08-07 01:03
I figured out how to move the files...all good here.

**Comment by daniel-isaacs** [comment] 2022-08-19 21:30
I am no longer seeing this issue when building a new site. Would it be possible for someone else that previously encountered the problem to give it a quick test? Thanks!

**Comment by jon419** [comment] 2022-08-22 18:34
@daniel-isaacs  - I have confirmed on our end that the latest main branch is working without this error.  We had it a couple weeks ago, but we are good now.

**Comment by daniel-isaacs** [comment] 2022-08-22 21:08
@jon419  Appreciate that! 

Going ahead and closing this.

**Closed by daniel-isaacs** 2022-08-22 21:08 UTC
