### ISSUE TITLE
Installation fails on step 6, if python2 is not installed

### ISSUE THREAD

**Issue by gatisb** [episerver/Foundation#757] opened 2021-11-17 11:23 UTC
**Describe the bug**
Installation fails on step 6, if python2 is not installed

**To Reproduce**
1. find a system with no python2 installed
2. try to install

**Expected behavior**
Installation succeeds

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
add link to: https://www.python.org/downloads/release/python-2718/ or something that installs it -> in 'System requirements' section

**Comment by zbrilhart** [comment] 2022-01-31 17:19
In addition to installing python 2, you also may have to update the npm config like in this post. 

https://stackoverflow.com/a/64486670/7077451

**Comment by daniel-isaacs** [comment] 2022-03-12 17:01
Caused by Node version issues -- workaround is to use Node 14.x.

Test branch with node package updates created but not fully verified: https://github.com/daniel-isaacs/Foundation/tree/node-package-updates

**Comment by lunchin** [comment] 2022-04-15 18:08
Closing the issue with requirement to use up to date node version

**Closed by lunchin** 2022-04-15 18:08 UTC
Labels: cms11
